### ISSUE TITLE
Error installing updated HydroSight V1.4.0

### ISSUE THREAD

**Issue by meeta-gupta** [peterson-tim-j/HydroSight#59] opened 2022-09-28 05:06 UTC
Hi Tim,
I installed the new version of HydroSight (1.4.0) and on running the code on MATLAB I received an error message on reading of the mat-file. Attached is the screenshot for your reference.
![HydroSight 1 4 0_Error](https://user-images.githubusercontent.com/114556386/192692047-a3e4e520-2695-4632-812f-ecd5cdd06f28.png)

**Comment by peterson-tim-j** [comment] 2022-09-29 05:34
Thanks for picking this up. 

The problem was caused by how GitHub handles large files and their inclusion in downloaded source code. Specifically, the large .mat example files are stored on GitHub using "Large File Storage" (lfs). The default is for these files to not be included in downloads. By including the .gitattributes file these lfs files are now included in the .zip files.

Anyway, I've tested that the latest release [(here)](https://github.com/peterson-tim-j/HydroSight/releases/tag/v1.4.0.2) works. But it would be great if you could confirm this and report back. Thanks.

**Comment by meeta-gupta** [comment] 2022-09-29 08:21
Hi Tim,
I installed the updated version and its working perfectly fine now. Thank you for your quick response and fix for the code.

**Comment by peterson-tim-j** [comment] 2022-09-29 08:29
Great. Good to hear. I'll now fully release the new version and close this bug.

**Closed by peterson-tim-j** 2022-09-29 08:29 UTC
